### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by mmr118** [ricardoAntolin/androidKotlinCleanArchitecture#1]
[Here](https://github.com/ricardoAntolin/androidKotlinCleanArchitecture/blob/462e444b32b34278b8f3b52d01775dbbd9a250e7/app/src/main/kotlin/com/rantolin/cleanarchitecture/presentation/ui/activities/MainActivity.kt#L41) you are referencing `drawerLayout`, but where is this variable declared/coming from?

**Comment by ricardoAntolin** [comment]
Hello! It is coming from XML [layout](https://github.com/ricardoAntolin/androidKotlinCleanArchitecture/blob/462e444b32b34278b8f3b52d01775dbbd9a250e7/app/src/main/res/layout/activity_main.xml#L5) though synthetic import
